{{- if and .Values.ingress.enabled .Values.ingress.openshift -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "dependency-track.fullname" . }}-frontend
  labels:
    app.kubernetes.io/component: frontend
    {{- include "dependency-track.labels" . | nindent 4 }}
spec:
  host: {{ .Values.ingress.host }}
  to:
    kind: Service
    name: {{ include "dependency-track.fullname" . }}-frontend
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{ end }}
