apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: frontend
    {{- include "dependency-track.labels" . | nindent 4 }}
  name: {{ include "dependency-track.fullname" . }}-frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/component: frontend
    {{- include "dependency-track.selectorLabels" . | nindent 4 }}
